-- LibertyTube - schema inicial do Supabase
-- Execute este arquivo no SQL Editor do projeto Supabase do LibertyTube.
-- Nunca coloque a chave service_role dentro do aplicativo.

create extension if not exists pgcrypto;

create table if not exists public.perfis_usuario (
    user_id uuid primary key references auth.users(id) on delete cascade,
    nome text not null default '',
    ativo boolean not null default false,
    expira_em date,
    material_vip boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.aulas (
    id bigint generated by default as identity primary key,
    titulo text not null,
    descricao text not null default '',
    link_url text not null default '',
    icone text not null default '',
    modulo text not null default '',
    duracao text not null default '',
    ordem integer not null default 0,
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.bonus (
    id bigint generated by default as identity primary key,
    titulo text not null,
    descricao text not null default '',
    link_url text not null default '',
    icone text not null default '',
    modulo text not null default '',
    duracao text not null default '',
    ordem integer not null default 0,
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.como_usar (
    id bigint generated by default as identity primary key,
    titulo text not null,
    descricao text not null default '',
    link_url text not null default '',
    icone text not null default '',
    modulo text not null default '',
    duracao text not null default '',
    ordem integer not null default 0,
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.material_exclusivo (
    id bigint generated by default as identity primary key,
    titulo text not null,
    descricao text not null default '',
    link_url text not null default '',
    icone text not null default '',
    modulo text not null default '',
    duracao text not null default '',
    ordem integer not null default 0,
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.config_app (
    chave text primary key,
    valor text not null default '',
    publico boolean not null default true,
    updated_at timestamptz not null default now()
);

create index if not exists aulas_ordem_idx on public.aulas (modulo, ordem);
create index if not exists bonus_ordem_idx on public.bonus (ordem);
create index if not exists como_usar_ordem_idx on public.como_usar (ordem);
create index if not exists material_exclusivo_ordem_idx
    on public.material_exclusivo (ordem);

-- Perfis sao criados automaticamente, mas precisam ser liberados pelo admin.
create or replace function public.libertytube_novo_usuario()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.perfis_usuario (user_id, nome, ativo)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'nome', ''),
        false
    )
    on conflict (user_id) do nothing;
    return new;
end;
$$;

drop trigger if exists libertytube_criar_perfil on auth.users;
create trigger libertytube_criar_perfil
    after insert on auth.users
    for each row execute function public.libertytube_novo_usuario();

-- Funcao usada pelas politicas sem expor perfis de outros usuarios.
create or replace function public.libertytube_usuario_ativo()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.perfis_usuario p
        where p.user_id = auth.uid()
          and p.ativo = true
          and (p.expira_em is null or p.expira_em >= current_date)
    );
$$;

create or replace function public.libertytube_usuario_vip()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.perfis_usuario p
        where p.user_id = auth.uid()
          and p.ativo = true
          and p.material_vip = true
          and (p.expira_em is null or p.expira_em >= current_date)
    );
$$;

alter table public.perfis_usuario enable row level security;
alter table public.aulas enable row level security;
alter table public.bonus enable row level security;
alter table public.como_usar enable row level security;
alter table public.material_exclusivo enable row level security;
alter table public.config_app enable row level security;

drop policy if exists perfis_select_proprio on public.perfis_usuario;
create policy perfis_select_proprio
    on public.perfis_usuario for select to authenticated
    using (user_id = auth.uid());

drop policy if exists aulas_select_ativos on public.aulas;
create policy aulas_select_ativos
    on public.aulas for select to authenticated
    using (ativo = true and public.libertytube_usuario_ativo());

drop policy if exists bonus_select_ativos on public.bonus;
create policy bonus_select_ativos
    on public.bonus for select to authenticated
    using (ativo = true and public.libertytube_usuario_ativo());

drop policy if exists como_usar_select_ativos on public.como_usar;
create policy como_usar_select_ativos
    on public.como_usar for select to authenticated
    using (ativo = true and public.libertytube_usuario_ativo());

drop policy if exists vip_select_liberados on public.material_exclusivo;
create policy vip_select_liberados
    on public.material_exclusivo for select to authenticated
    using (ativo = true and public.libertytube_usuario_vip());

drop policy if exists config_select_publica on public.config_app;
create policy config_select_publica
    on public.config_app for select to anon, authenticated
    using (publico = true);

grant select on public.perfis_usuario to authenticated;
grant select on public.aulas to authenticated;
grant select on public.bonus to authenticated;
grant select on public.como_usar to authenticated;
grant select on public.material_exclusivo to authenticated;
grant select on public.config_app to anon, authenticated;
grant execute on function public.libertytube_usuario_ativo() to authenticated;
grant execute on function public.libertytube_usuario_vip() to authenticated;

insert into public.config_app (chave, valor, publico)
values
    ('whatsapp_suporte', '', true),
    ('whatsapp_grupo', '', true)
on conflict (chave) do nothing;
